# Generated by Django 5.2.1 on 2025-06-19 05:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('date_published', models.DateField(default=django.utils.timezone.now)),
                ('cover', models.ImageField(default='book_covers/placeholder_cover.png', upload_to='book_covers/')),
                ('description', models.TextField(default='No description available.', max_length=2500)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('borrow_count', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('featured_type', models.CharField(choices=[('popular', 'Popular'), ('latest', 'Latest'), ('custom', 'Custom')], verbose_name='Type')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('library', 'Books'), ('genre', 'Genre')], verbose_name='Page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines display order within the same page.')),
                ('books', models.ManyToManyField(blank=True, help_text="Only accessible with 'Custom' type.\nRequired: Books must share the same genre if specified.", to='Application.book')),
                ('genre', models.ForeignKey(blank=True, help_text="Required if Page is 'Genre': Determines which genre page this section appears on.", null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.genre')),
            ],
            options={
                'verbose_name_plural': 'Featured',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='Application.genre'),
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='Application.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Records',
            },
        ),
    ]
