# Generated by Django 5.2.1 on 2025-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='featured',
            name='books',
            field=models.ManyToManyField(blank=True, help_text="Only accessible with 'Custom' type.<br>Required: Books must share the same genre if specified.<br>", to='Application.book'),
        ),
    ]
