# Generated by Django 5.2.1 on 2025-06-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_book_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.BigIntegerField(default=0),
        ),
    ]
