# Generated by Django 5.2.1 on 2025-06-23 09:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_alter_book_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_quantity',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
