# Generated by Django 5.2 on 2025-06-24 00:29

import Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_alter_book_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, unique=True, validators=[Application.models.validate_isbn]),
        ),
        migrations.AlterField(
            model_name='book',
            name='total_quantity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
