# Generated by Django 5.2 on 2025-06-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_book_isbn_alter_book_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
