# Generated by Django 5.2 on 2025-06-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_alter_featured_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
