# Generated by Django 5.2.1 on 2025-06-26 00:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_alter_featured_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='genre',
            field=models.ForeignKey(blank=True, help_text="Required if Page is 'Genre': Determines which genre page this section appears on.<br>Optional for other types of pages: Deternmines what genre of books will be displayed.", null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.genre'),
        ),
        migrations.AlterField(
            model_name='featured',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Determines display order within the same page.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
