# Generated by Django 5.2.1 on 2025-06-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_alter_featured_genre_alter_featured_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Determines display order within the same page.'),
        ),
    ]
