# Generated by Django 5.2.1 on 2025-06-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_alter_featured_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, default='No description available.', max_length=2500),
        ),
    ]
