# Generated by Django 5.2 on 2025-06-27 01:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_alter_book_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='BorrowRecord',
        ),
        migrations.AlterModelOptions(
            name='borrowrecord',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
    ]
