# Generated by Django 5.2 on 2025-05-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_rename_isbn_book_isbn_rename_image_book_cover_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Library'},
        ),
    ]
