# Generated by Django 5.2 on 2025-06-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_rename_quantity_book_total_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description available.', max_length=2500),
        ),
    ]
