# Generated by Django 5.2 on 2025-06-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_genre_book_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryrecords',
            options={'verbose_name_plural': 'Records'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='Application.genre'),
        ),
    ]
