# Generated by Django 5.2 on 2025-06-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_libraryrecords_due_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libraryrecords',
            unique_together=set(),
        ),
    ]
