# Generated by Django 5.2.1 on 2025-06-06 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_alter_libraryrecords_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LibraryRecords',
            new_name='Library',
        ),
    ]
