# Generated by Django 5.2.1 on 2025-06-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_rename_libraryrecords_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popularity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
