# Generated by Django 5.2.1 on 2025-06-18 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_book_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='popularity',
            new_name='borrow_count',
        ),
    ]
