# Generated by Django 5.2.1 on 2025-06-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_rename_popularity_book_borrow_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('featured_type', models.CharField(choices=[('popular', 'Popular'), ('latest', 'Latest'), ('custom', 'Custom')], verbose_name='Type')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('library', 'Books'), ('genre', 'Genre')], verbose_name='Page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines display order within the same page.')),
                ('books', models.ManyToManyField(blank=True, help_text="Only accessible with 'Custom' type.\nRequired: Books must share the same genre if specified.", to='Application.book')),
                ('genre', models.ForeignKey(blank=True, help_text="Required if Page is 'Genre': Determines which genre page this section appears on.", null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.genre')),
            ],
            options={
                'verbose_name_plural': 'Featured',
            },
        ),
    ]
